### ISSUE TITLE
Custom Property as Tags

### ISSUE THREAD

**Issue by raytopianprojects** [lifelandman/omUlette#1]
Awesome library btw! 

Currently custom properties are not exported. This could be solved with the tag syntax: https://docs.panda3d.org/1.10/python/pipeline/egg-files/syntax#tag

**Comment by lifelandman** [comment]
Custom String Properties should be exporting as tags. Are your custom properties not string properties? if that is not the issue, may I have more information on the nature of your issue?

**Comment by raytopianprojects** [comment]
I see now! I had try exporting a model with a float property on it. 

Would it be possible to export most of the properties as strings even if they are not strings? Being able to do so would simply editing those values.

**Comment by lifelandman** [comment]
I just pushed a commit that allows all types of properties. If you want you can download and zip "omulette_main" to create a binary to install from disc, but I think I might wait to put this in a release until ~~I fix another obvious bug~~ if/when the morph-slider update is ready.
